var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/project/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__07v_-rn._.js")
R.c("server/chunks/ssr/_1hxp0t4._.js")
R.c("server/chunks/ssr/_1huddo1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0u5c9-h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0wpkx2d.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d8500-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__167g_4s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_project_[id]_page_actions_1pgszwu.js")
R.m(56529)
module.exports=R.m(56529).exports
