// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/artifact/[slug]" | "/dashboard" | "/explore" | "/fuse" | "/login" | "/plan" | "/project/[id]" | "/register" | "/remix/[slug]" | "/resources" | "/settings" | "/u/[id]"
type AppRouteHandlerRoutes = "/api/apps/[slug]/icon.svg" | "/api/apps/[slug]/kv/[key]" | "/api/apps/[slug]/manifest.webmanifest" | "/api/apps/[slug]/report" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/connectors/[name]" | "/api/credits" | "/api/credits/claim" | "/api/credits/redeem" | "/api/domains/check" | "/api/health" | "/api/jobs/[jobId]/stream" | "/api/plan" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/attachments" | "/api/projects/[id]/attachments/[attId]" | "/api/projects/[id]/deploy" | "/api/projects/[id]/deploy/[depId]" | "/api/projects/[id]/generate" | "/api/projects/[id]/publish" | "/api/projects/[id]/reports" | "/api/projects/[id]/rollback" | "/api/templates" | "/api/templates/[id]/preview" | "/api/user" | "/d/[name]" | "/p/[slug]" | "/p/[slug]/sw.js" | "/p/[slug]/v/[seq]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/apps/[slug]/icon.svg": { "slug": string; }
  "/api/apps/[slug]/kv/[key]": { "slug": string; "key": string; }
  "/api/apps/[slug]/manifest.webmanifest": { "slug": string; }
  "/api/apps/[slug]/report": { "slug": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/connectors/[name]": { "name": string; }
  "/api/credits": {}
  "/api/credits/claim": {}
  "/api/credits/redeem": {}
  "/api/domains/check": {}
  "/api/health": {}
  "/api/jobs/[jobId]/stream": { "jobId": string; }
  "/api/plan": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/attachments": { "id": string; }
  "/api/projects/[id]/attachments/[attId]": { "id": string; "attId": string; }
  "/api/projects/[id]/deploy": { "id": string; }
  "/api/projects/[id]/deploy/[depId]": { "id": string; "depId": string; }
  "/api/projects/[id]/generate": { "id": string; }
  "/api/projects/[id]/publish": { "id": string; }
  "/api/projects/[id]/reports": { "id": string; }
  "/api/projects/[id]/rollback": { "id": string; }
  "/api/templates": {}
  "/api/templates/[id]/preview": { "id": string; }
  "/api/user": {}
  "/artifact/[slug]": { "slug": string; }
  "/d/[name]": { "name": string; }
  "/dashboard": {}
  "/explore": {}
  "/fuse": {}
  "/login": {}
  "/p/[slug]": { "slug": string; }
  "/p/[slug]/sw.js": { "slug": string; }
  "/p/[slug]/v/[seq]": { "slug": string; "seq": string; }
  "/plan": {}
  "/project/[id]": { "id": string; }
  "/register": {}
  "/remix/[slug]": { "slug": string; }
  "/resources": {}
  "/settings": {}
  "/u/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
