// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(shell)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shell)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shell)/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plan">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shell)/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shell)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/artifact/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artifact/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/artifact/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../src/app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fuse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fuse">> = Specific
  const handler = {} as typeof import("../../src/app/fuse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/project/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/remix/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/remix/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/remix/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/u/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/u/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/[slug]/icon.svg/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/[slug]/icon.svg">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/[slug]/icon.svg/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/[slug]/kv/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/[slug]/kv/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/[slug]/kv/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/[slug]/manifest.webmanifest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/[slug]/manifest.webmanifest">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/[slug]/manifest.webmanifest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/apps/[slug]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/apps/[slug]/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/apps/[slug]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/connectors/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connectors/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/api/connectors/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits/claim">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits/redeem">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/domains/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/domains/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/domains/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[jobId]/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[jobId]/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[jobId]/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/attachments/[attId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/attachments/[attId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/attachments/[attId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/attachments">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/deploy/[depId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/deploy/[depId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/deploy/[depId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/deploy">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/rollback">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/[id]/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/d/[name]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/d/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/d/[name]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/p/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/p/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/p/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/p/[slug]/sw.js/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/p/[slug]/sw.js">> = Specific
  const handler = {} as typeof import("../../src/app/p/[slug]/sw.js/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/p/[slug]/v/[seq]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/p/[slug]/v/[seq]">> = Specific
  const handler = {} as typeof import("../../src/app/p/[slug]/v/[seq]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(shell)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(shell)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
