var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[id]/generate/route.js")
R.c("server/chunks/[root-of-the-server]__0d2jdxq._.js")
R.c("server/chunks/[root-of-the-server]__0a84a23._.js")
R.c("server/chunks/_0htkyro._.js")
R.c("server/chunks/_0ran56h._.js")
R.c("server/chunks/[root-of-the-server]__1y_g68p._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_projects_[id]_generate_route_actions_1tfzn6c.js")
R.m(14823)
module.exports=R.m(14823).exports
