var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(shell)/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1_3wf2o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_15r-rkj.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d8500-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__167g_4s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__1hv__0n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1h4k0e-._.js")
R.c("server/chunks/ssr/_1hxp0t4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(shell)_settings_page_actions_1t3m5--.js")
R.m(1006)
module.exports=R.m(1006).exports
