var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/u/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a5_-dz._.js")
R.c("server/chunks/ssr/_1huddo1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0bw_x_7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0u5c9-h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1r8l7fs.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d8500-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1map00z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__167g_4s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_u_[id]_page_actions_0e2u9kb.js")
R.m(70566)
module.exports=R.m(70566).exports
